config/routes.rb
Rails.application.routes.draw do

  
  resources :workers

  
end

app/models/worker.rb
class Worker < ActiveRecord::Base

def create
end

def new
end

def self.search(search)

   @testw = where(['name LIKE ?', "%#{search}%"])
   


end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController



    def new
	@worker = Worker.new   
	end
	

	 def index
	  @workers= Worker.all
	  @testw = Worker.search(params[:search])
	  end

	def show

	end

	def create
		@worker = Worker.new(worker_params)
		@worker.save
		redirect_to @worker
	end

   def update
   end

     def destroy
     	end



   def worker_params
 	params.require(:worker).permit(:name, :lastname, :occupation, :phone, :references, :descript)
   end
   
  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myapp2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body  style="background-color: #009999;">
<nav class="navbar navbar-default" role="navigation">
	<!-- Brand and toggle get grouped for better mobile display -->
	<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
		<a class="navbar-brand" href="#">Title</a>
	</div>

	<!-- Collect the nav links, forms, and other content for toggling -->
	<div class="collapse navbar-collapse navbar-ex1-collapse">
		<ul class="nav navbar-nav">
			<li  class="active">
		    <%=link_to "NEW", new_worker_path();%></li>
			<li><%=link_to "LISTA", workers_path(); %></li>
		</ul>
		<form class="navbar-form navbar-left" role="search">
			<div class="form-group">
		
					<%=form_tag workers_path, :method => 'get' do %>
				    <class="form-control" placeholder="Search"><%= text_field_tag :search, params[:search] %>
				    <%= submit_tag "Search", :name => nil %>
                    <%end%>
			</div>
			
		</form>
		<ul class="nav navbar-nav navbar-right">
			<li><a href="#">Link</a></li>
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
				<ul class="dropdown-menu">
					<li><a href="#">Action</a></li>
					<li><a href="#">Another action</a></li>
					<li><a href="#">Something else here</a></li>
					<li><a href="#">Separated link</a></li>
				</ul>
			</li>
		</ul>
	</div><!-- /.navbar-collapse -->
</nav>

<%= yield %>

</body>
</html>

app/views/workers/index.html.erb
<!DOCTYPE html>
<head>

</head>
<body>


  



 <% @workers.each do |worker| %>
 <p> <%= worker.name %> 
  <%= worker.lastname %> 
   <%= worker.occupation %> 
    <%= worker.phone %> 
     <%= worker.descript %> 
      <% end %>
     </p>


      <% @testw.each do |worker| %>
 <p> <%= worker.name %> 
  <%= worker.lastname %> 
   <%= worker.occupation %> 
    <%= worker.phone %> 
     <%= worker.descript %> 
      <% end %></p>



</body>

app/views/workers/new.html.erb
<!DOCTYPE html>
<head>

</head>
<body>
<div style="float: right";>
<%= simple_form_for @worker do |f| %>
 <p class="emb">
  <%= f.label :ime%>
  <%= f.text_field :name %></p>
   <p class="emb">
  <%= f.label :prezime%>
  <%= f.text_field :lastname %></p>
  <p class="emb">
  <%= f.label :zanimanje%>
  <%= f.text_field :occupation %>
  <p class="emb">
  <%= f.label :telefon%>
  <%= f.text_field :phone %>
  <p class="emb">
  <%= f.label :preporuke%>
  <%= f.text_field :references %>
  <p class="emb">
  <%= f.label :opis%>
  <%= f.text_field :descript %></br>
  <%= f.submit  "create" %>
  <% redirect_to :back %>
<% end %>
</div>


</body>



app/views/workers/show.html.erb
<!DOCTYPE html>
<head>

</head>
<body>
<p> Delila </p>

</body>

app/views/workers/update.html.erb
update.html.erb